---
## local mode:
## ansible-playbook x.yml --connection=local

- hosts: cross
  remote_user: root
#  gather_facts: false

  tasks:
  - name: command 1
    shell: sleep 10
    register: result1
    async: 15
    poll: 0 # 0 for aysnc, others for sync check per X seconds.

#  - pause: prompt="pause here, ctrl+C to select options."

  - wait_for: path=/tmp/ans state=present

#  - debug: msg="System has gateway {{ ansible_default_ipv4.gateway }}"
#    when: ansible_default_ipv4.gateway is defined

  - name: command 2
    shell: sleep 5 
    register: result2 

#  - debug: msg="debug {{ result2 }}"
  - debug: var=result2










#  vars:
#    hostcount: 5
#  tasks:
#    - name: Print interface
#      debug: msg="{{ item }}/aa"
#      with_items: "{{ ansible_interfaces }}"


#  tasks:
#  - name: echo command
#    shell: echo cross - {{ ansible_default_ipv4.gateway }} >> /tmp/abc

#  - debug: msg="System has gateway" "{{ ansible_default_ipv4.gateway }}"
#    when: ansible_default_ipv4.gateway is defined

#  tasks:
#  - name: exec shell
##    shell: chdir=/opt sh 1.sh
#    shell: /usr/bin/uptime
#    register: result 
##    debug: msg="debug: {{ result }} "
