- hosts: sbc
#  remote_user: root
  remote_user: caiex
  sudo: yes

  tasks:
#   - name: cp
#     shell: cp /opt/apache-tomcat-7.0.63/webapps/SBC/WEB-INF/classes/jdbc.properties /opt/CONF/SBC

   - name: rm SBC
     shell: chdir=/opt/apache-tomcat-7.0.63/webapps/ rm -rf SBC*

   - name: copy war
     copy: src=/opt/apache-tomcat-7.0.63/webapps/SBC.war dest=/tmp

   - name: copy config
     shell: mv /tmp/SBC.war /opt/apache-tomcat-7.0.63/webapps/

   - name: sleep for a while
     shell: sleep 15

#   - name: stop tomcat
#     shell: initctl stop tomcat
#     service: name=tomcat state=stopped

#   - name: sleep for a while
#     shell: sleep 10
#
   - name: cp
     shell: chdir=/opt/CONF/SBC cp jdbc.properties /opt/apache-tomcat-7.0.63/webapps/SBC/WEB-INF/classes/ 
     notify: 
      - restart tomcat
#
#   - name: ensure tomcat is running
#     service: name=tomcat state=started
    
  handlers: 
   - name: restart tomcat
     service: name=tomcat state=restarted
