
- hosts: test
  remote_user: root
  tasks:
#  - name: cp JDK    到底放到哪儿是个问题
#    shell: cp jdk-7u79-linux-x64.tar.gz
#  - name: update config
#    shell: update-alternatives --config java

  - name: wait on user input
    pause: prompt="Please select a choice:"

