- hosts: cross
  remote_user: root

  tasks:
  - name: echo command
    shell: echo cross - {{ ansible_default_ipv4.gateway }} >> /tmp/abc

#  - debug: msg="System has gateway" "{{ ansible_default_ipv4.gateway }}"
#    when: ansible_default_ipv4.gateway is defined

#  tasks:
#  - name: exec shell
##    shell: chdir=/opt sh 1.sh
#    shell: /usr/bin/uptime
#    register: result 
##    debug: msg="debug: {{ result }} "
